language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - openjdk7
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 0c99fdce5fc19f504408302d3444729c2126096f
  keep_history: true
on:
  branch: master
