language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - openjdk7
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    branch: master
