language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - openjdk7
deploy:
  provider: pages
  skip_cleanup: true
  github_token: gh_token
  keep_history: true
on:
  branch: master
