language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - openjdk7
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 873e96dcace0436987dfa008807f7b06a9e49d22
  keep_history: true
on:
  branch: master
